# Generated by Django 3.2.10 on 2021-12-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='username',
        ),
    ]
