# Generated by Django 3.2.10 on 2021-12-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_remove_github_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='githubuser',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='github',
            old_name='imagelink',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='github',
            name='user_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
