# Generated by Django 3.2.10 on 2021-12-20 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0004_remove_github_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='github',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='github',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
