# Generated by Django 3.2.10 on 2021-12-20 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0007_auto_20211220_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2021, 12, 20, 10, 39, 36, 374698, tzinfo=utc)),
        ),
    ]
