# Generated by Django 3.2.10 on 2021-12-20 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0011_auto_20211220_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='contact_info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='github',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2021, 12, 20, 21, 16, 2, 207653, tzinfo=utc)),
        ),
    ]
