# Generated by Django 3.2.10 on 2021-12-20 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0012_auto_20211221_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='contact_info',
        ),
        migrations.AlterField(
            model_name='github',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2021, 12, 20, 21, 31, 5, 916577, tzinfo=utc)),
        ),
    ]
