# Generated by Django 3.2.10 on 2021-12-20 22:31

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0014_auto_20211221_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='project_count',
        ),
        migrations.AlterField(
            model_name='github',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2021, 12, 20, 22, 31, 58, 213859, tzinfo=utc)),
        ),
    ]
