# Generated by Django 3.2.10 on 2021-12-22 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0017_alter_github_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2021, 12, 22, 12, 59, 36, 390675, tzinfo=utc)),
        ),
    ]
